"use strict";
// Ideally, we would import from @fluentui/react-icons rather than deep imports.
// However, the react-icons package is very expensive to parse for the TypeScript compiler for this package AND its dependencies.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.Filter20Regular = exports.Emoji20Regular = exports.DoorArrowLeft20Regular = exports.DocumentLink20Regular = exports.DocumentBulletList20Regular = exports.DocumentBulletList20Filled = exports.DocumentAdd20Regular = exports.Dismiss20Regular = exports.Delete20Regular = exports.ChevronUpDown16Regular = exports.ChevronRight16Regular = exports.ChevronDown16Regular = exports.Checkmark16Regular = exports.Warning20Filled = exports.StarOff20Filled = exports.Star20Regular = exports.Search20Regular = exports.Rename20Regular = exports.PeopleAdd20Regular = exports.People20Regular = exports.MoreVertical20Regular = exports.MoreHorizontal20Regular = exports.LockClosed20Regular = exports.List20Regular = exports.Grid20Regular = exports.Add20Regular = void 0;
var chunk_0_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-0");
__createBinding(exports, chunk_0_1, "Add20Regular");
var chunk_10_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-10");
__createBinding(exports, chunk_10_1, "Grid20Regular");
var chunk_11_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-11");
__createBinding(exports, chunk_11_1, "List20Regular");
__createBinding(exports, chunk_11_1, "LockClosed20Regular");
var chunk_12_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-12");
__createBinding(exports, chunk_12_1, "MoreHorizontal20Regular");
__createBinding(exports, chunk_12_1, "MoreVertical20Regular");
var chunk_13_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-13");
__createBinding(exports, chunk_13_1, "People20Regular");
__createBinding(exports, chunk_13_1, "PeopleAdd20Regular");
var chunk_14_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-14");
__createBinding(exports, chunk_14_1, "Rename20Regular");
var chunk_15_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-15");
__createBinding(exports, chunk_15_1, "Search20Regular");
var chunk_16_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-16");
__createBinding(exports, chunk_16_1, "Star20Regular");
__createBinding(exports, chunk_16_1, "StarOff20Filled");
var chunk_20_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-20");
__createBinding(exports, chunk_20_1, "Warning20Filled");
var chunk_4_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-4");
__createBinding(exports, chunk_4_1, "Checkmark16Regular");
__createBinding(exports, chunk_4_1, "ChevronDown16Regular");
__createBinding(exports, chunk_4_1, "ChevronRight16Regular");
__createBinding(exports, chunk_4_1, "ChevronUpDown16Regular");
var chunk_6_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-6");
__createBinding(exports, chunk_6_1, "Delete20Regular");
var chunk_7_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-7");
__createBinding(exports, chunk_7_1, "Dismiss20Regular");
__createBinding(exports, chunk_7_1, "DocumentAdd20Regular");
__createBinding(exports, chunk_7_1, "DocumentBulletList20Filled");
__createBinding(exports, chunk_7_1, "DocumentBulletList20Regular");
__createBinding(exports, chunk_7_1, "DocumentLink20Regular");
var chunk_8_1 = require("@fluentui/react-icons/lib/sizedIcons/chunk-8");
__createBinding(exports, chunk_8_1, "DoorArrowLeft20Regular");
__createBinding(exports, chunk_8_1, "Emoji20Regular");
__createBinding(exports, chunk_8_1, "Filter20Regular");
