"use strict";
// Ideally, we would import from @fluentui/react-icons rather than deep imports.
// However, the react-icons package is very expensive to parse for the TypeScript compiler for this package AND its dependencies.
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.Emoji20Regular = exports.Search20Regular = exports.Checkmark16Regular = exports.Warning20Filled = exports.StarOff20Filled = exports.Rename20Regular = exports.PeopleAdd20Regular = exports.People20Regular = exports.DocumentAdd20Regular = exports.MoreVertical20Regular = exports.MoreHorizontal20Regular = exports.LockClosed20Regular = exports.List20Regular = exports.DoorArrowLeft20Regular = exports.Grid20Regular = exports.Filter20Regular = exports.Star20Regular = exports.Dismiss20Regular = exports.Delete20Regular = exports.ChevronUpDown16Regular = exports.ChevronDown16Regular = exports.ChevronRight16Regular = exports.DocumentBulletList20Filled = exports.DocumentBulletList20Regular = exports.DocumentLink20Regular = exports.Add20Regular = void 0;
var Add20Regular_1 = require("@fluentui/react-icons/lib/esm/components/Add20Regular");
__createBinding(exports, Add20Regular_1, "default", "Add20Regular");
var DocumentLink20Regular_1 = require("@fluentui/react-icons/lib/esm/components/DocumentLink20Regular");
__createBinding(exports, DocumentLink20Regular_1, "default", "DocumentLink20Regular");
var DocumentBulletList20Regular_1 = require("@fluentui/react-icons/lib/esm/components/DocumentBulletList20Regular");
__createBinding(exports, DocumentBulletList20Regular_1, "default", "DocumentBulletList20Regular");
var DocumentBulletList20Filled_1 = require("@fluentui/react-icons/lib/esm/components/DocumentBulletList20Filled");
__createBinding(exports, DocumentBulletList20Filled_1, "default", "DocumentBulletList20Filled");
var ChevronRight16Regular_1 = require("@fluentui/react-icons/lib/esm/components/ChevronRight16Regular");
__createBinding(exports, ChevronRight16Regular_1, "default", "ChevronRight16Regular");
var ChevronDown16Regular_1 = require("@fluentui/react-icons/lib/esm/components/ChevronDown16Regular");
__createBinding(exports, ChevronDown16Regular_1, "default", "ChevronDown16Regular");
var ChevronUpDown16Regular_1 = require("@fluentui/react-icons/lib/esm/components/ChevronUpDown16Regular");
__createBinding(exports, ChevronUpDown16Regular_1, "default", "ChevronUpDown16Regular");
var Delete20Regular_1 = require("@fluentui/react-icons/lib/esm/components/Delete20Regular");
__createBinding(exports, Delete20Regular_1, "default", "Delete20Regular");
var Dismiss20Regular_1 = require("@fluentui/react-icons/lib/esm/components/Dismiss20Regular");
__createBinding(exports, Dismiss20Regular_1, "default", "Dismiss20Regular");
var Star20Regular_1 = require("@fluentui/react-icons/lib/esm/components/Star20Regular");
__createBinding(exports, Star20Regular_1, "default", "Star20Regular");
var Filter20Regular_1 = require("@fluentui/react-icons/lib/esm/components/Filter20Regular");
__createBinding(exports, Filter20Regular_1, "default", "Filter20Regular");
var Grid20Regular_1 = require("@fluentui/react-icons/lib/esm/components/Grid20Regular");
__createBinding(exports, Grid20Regular_1, "default", "Grid20Regular");
var DoorArrowLeft20Regular_1 = require("@fluentui/react-icons/lib/esm/components/DoorArrowLeft20Regular");
__createBinding(exports, DoorArrowLeft20Regular_1, "default", "DoorArrowLeft20Regular");
var List20Regular_1 = require("@fluentui/react-icons/lib/esm/components/List20Regular");
__createBinding(exports, List20Regular_1, "default", "List20Regular");
var LockClosed20Regular_1 = require("@fluentui/react-icons/lib/esm/components/LockClosed20Regular");
__createBinding(exports, LockClosed20Regular_1, "default", "LockClosed20Regular");
var MoreHorizontal20Regular_1 = require("@fluentui/react-icons/lib/esm/components/MoreHorizontal20Regular");
__createBinding(exports, MoreHorizontal20Regular_1, "default", "MoreHorizontal20Regular");
var MoreVertical20Regular_1 = require("@fluentui/react-icons/lib/esm/components/MoreVertical20Regular");
__createBinding(exports, MoreVertical20Regular_1, "default", "MoreVertical20Regular");
var DocumentAdd20Regular_1 = require("@fluentui/react-icons/lib/esm/components/DocumentAdd20Regular");
__createBinding(exports, DocumentAdd20Regular_1, "default", "DocumentAdd20Regular");
var People20Regular_1 = require("@fluentui/react-icons/lib/esm/components/People20Regular");
__createBinding(exports, People20Regular_1, "default", "People20Regular");
var PeopleAdd20Regular_1 = require("@fluentui/react-icons/lib/esm/components/PeopleAdd20Regular");
__createBinding(exports, PeopleAdd20Regular_1, "default", "PeopleAdd20Regular");
var Rename20Regular_1 = require("@fluentui/react-icons/lib/esm/components/Rename20Regular");
__createBinding(exports, Rename20Regular_1, "default", "Rename20Regular");
var StarOff20Filled_1 = require("@fluentui/react-icons/lib/esm/components/StarOff20Filled");
__createBinding(exports, StarOff20Filled_1, "default", "StarOff20Filled");
var Warning20Filled_1 = require("@fluentui/react-icons/lib/esm/components/Warning20Filled");
__createBinding(exports, Warning20Filled_1, "default", "Warning20Filled");
var Checkmark16Regular_1 = require("@fluentui/react-icons/lib/esm/components/Checkmark16Regular");
__createBinding(exports, Checkmark16Regular_1, "default", "Checkmark16Regular");
var Search20Regular_1 = require("@fluentui/react-icons/lib/esm/components/Search20Regular");
__createBinding(exports, Search20Regular_1, "default", "Search20Regular");
var Emoji20Regular_1 = require("@fluentui/react-icons/lib/esm/components/Emoji20Regular");
__createBinding(exports, Emoji20Regular_1, "default", "Emoji20Regular");
